name: teamcity

services:
  teamcity-server:
    image: jetbrains/teamcity-server
    container_name: teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - teamcity_data:/data/teamcity_server/datadir
      - teamcity_logs:/opt/teamcity/logs
    restart: unless-stopped

  teamcity-agent:
    image: jetbrains/teamcity-agent
    container_name: teamcity-agent-01
    depends_on:
      - teamcity-server
    environment:
      SERVER_URL: http://teamcity-server:8111
      AGENT_NAME: docker-agent-01
    volumes:
      - teamcity_agent:/opt/buildagent
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  teamcity_data:
  teamcity_logs:
  teamcity_agent:
